### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by woddy68** [SergKolo/launcher-list-indicator#10]
I installed this applet on my desktop PC and it works perfectly on my notebook (new Ubuntu 16.04 installation)  not start.
By starting from the terminal I get this error :
`-Aspire-E1-522:~$ launcher-list-indicator
Traceback (most recent call last):
  File "/usr/bin/launcher-list-indicator", line 370, in <module>
    main()
  File "/usr/bin/launcher-list-indicator", line 366, in main
    indicator = LauncherListIndicator()
  File "/usr/bin/launcher-list-indicator", line 81, in **init**
    self.update()
  File "/usr/bin/launcher-list-indicator", line 330, in update
    glib.timeout_add_seconds(timeout, self.callback)
UnboundLocalError: local variable 'timeout' referenced before assignment

`
Sorry for my English. Hello

**Comment by SergKolo** [comment]
@woddy68  you're probably using the older version from PPA,  right ? This has been already fixed here on github. Take the zip archive https://github.com/SergKolo/launcher-list-indicator/archive/master.zip

**Comment by woddy68** [comment]
Perfect, it works.
Thank you very much
