### ISSUE TITLE
Fails to start with "AttributeError: 'LauncherListIndicator' object has no attribute 'icon_path'"

### ISSUE THREAD

**Issue by hotice** [SergKolo/launcher-list-indicator#11]
Launcher List Indicator fails to start with the following error:

```
$ launcher-list-indicator 
Traceback (most recent call last):
  File "/usr/bin/launcher-list-indicator", line 524, in <module>
    main()
  File "/usr/bin/launcher-list-indicator", line 520, in main
    indicator = LauncherListIndicator()
  File "/usr/bin/launcher-list-indicator", line 81, in __init__
    os.path.join(self.icon_path, "indicator-icon.png")
AttributeError: 'LauncherListIndicator' object has no attribute 'icon_path'
```

This only occurs on fresh installs. To reproduce the issue, simply remove the ~/.local/share/icons/launcher-list-indicator folder and try to launch the indicator.

The issue occurs because the indicator looks for "indicator-icon.png" icon in ~/.local/share/icons/launcher-list-indicator and this folder (and thus, the icon) is not created by the indicator. Creating this folder manually and copying the icon there fixes the issue.

**Comment by SergKolo** [comment]
Fix added, there was typo in the if - else statement. Also , ensured that the the `self.icon_path` variable is set

**Comment by hotice** [comment]
Fixed, thank you!
