### ISSUE TITLE
Crashes at launch

### ISSUE THREAD

**Issue by elmerehbi** [SergKolo/launcher-list-indicator#14]
Thank you for the wonderful concept. I just added the ppa & installed it. Unfortunately it crashes at launch.

OS: Ubuntu Gnome 16.04

I guess you didn't implement it for Gnome yet? Would i be possible to do so? Thanks

**Comment by SergKolo** [comment]
@elmerehbi Yes, unfortunately this particular implementation is specific for Unity desktop. Eventually I will try to make one for Gnome, however Gnome is a bit trickier when it comes to app indicators
