### ISSUE TITLE
Feature request: update profile

### ISSUE THREAD

**Issue by mauglee** [SergKolo/launcher-list-indicator#16]
If I add additional application to launcher, then press „save current“ in your indicator, and then enter same profile name, I am getting an error that such a profile already exists. Would be nice to have possibility to update it.
Now I can achieve this only by manually adding an entry to `.launcher_profiles.json`.

**Comment by SergKolo** [comment]
@mauglee  That can be done, I'll just remove the restriction on saving the profile under same name. This indicator was using code from another indicator that i made in past, so the restriction was necessary there, but not necessary here anymore. I'll let you know once I've pushed the fixes here

**Comment by mauglee** [comment]
Cool! For me your application is very useful. Thanks!

**Comment by SergKolo** [comment]
@mauglee  I've removed the restriction on saving profile, so now you should be able to update existing profile , just make sure you type in the same name.  If you installed from PPA, please wait 48 hours for the code to be imported into PPA. You can also just take the code from github and install everything manually if you'd like.

 As for your other feature request, I will be working on creating a preferences dialog , and will add a few features that you requested to that dialog. Currently my university and work schedule doesn't allow spending more time on working on this indicator (which I'm developing only in my spare time ), but I think I will have more time in November. There will be more things to come. I've a list of things I want to add, so there will be whole bunch of things coming to new release, but it will need some time.
