### ISSUE TITLE
Minor Suggestion

### ISSUE THREAD

**Issue by MathUHenry** [SergKolo/launcher-list-indicator#2]
Sorry to post this as an issue. I haven't figured out how to send a message in GitHub.

Please consider putting a checkmark next to the active launcher in the dropdown rather than on the bar (to save space).

Thank you for the Launcher Switcher!
![suggestion](https://cloud.githubusercontent.com/assets/21244313/17975399/7d6dd29c-6ab7-11e6-8baa-9b9f3c8b2e99.png)

**Comment by SergKolo** [comment]
@MathUHenry  Noted. I will see if I can add it as a menuentry to the indicator itself so that users can switch between having a label or checkmark.  Would command-line option be OK ?

**Comment by MathUHenry** [comment]
I think that's a great idea. Command-line works fine for me.
Again, thank you. This feature adds a lot of polish.

**Comment by alecive** [comment]
I agree with @MathUHenry , it is way more elegant to have only the icon in the top bar. @SergKolo I would suggest to use the checkmark as default :)

**Comment by SergKolo** [comment]
@alecive  I'll make it default. I'm actually thinking of adding a menu option for enabling/disabling the label.

**Comment by SergKolo** [comment]
Howdy, folks ! I pushed update to the indicator. Now it defaults to icon only. Label can be enabled via "Extras" submenu.

**Comment by MathUHenry** [comment]
Thank you!

**Comment by alecive** [comment]
:+1:
