### ISSUE TITLE
Feature request : shortcut

### ISSUE THREAD

**Issue by frdrcv** [SergKolo/launcher-list-indicator#4]
It would be great to add a shortcut to switch between profiles instead of having to click on the icon each time.

**Comment by SergKolo** [comment]
@frdrcv Shortcuts are  not typically  implemented with indicators.   I am planning  on adding scroll action to the indicator,  where hovering over icon and scrolling will activate next entry.  That's  the closest that can be done to shortcut.  Let me know if that's  a sufficient  alternative

**Comment by frdrcv** [comment]
I would enjoy that too, sure. Great work by the way!

**Comment by SergKolo** [comment]
@frdrcv  scroll action has been added. Let me know if you have any other suggestions :) Thanks for using my indicator
