### ISSUE TITLE
High cpu load on update()

### ISSUE THREAD

**Issue by slawekmikula** [SergKolo/launcher-list-indicator#6]
Ubuntu 14.04. Installed from PPA. When running there is high cpu load (~10%) for applet. 

Disabling or changing (in the code) update refresh to 5 seconds (form 0.75) causes cpu load to dissapear.

**Comment by SergKolo** [comment]
@slawekmikula I can increase the time but not up to 5 seconds - that's too much and will affect the other options of the indicator and refresh rate for the label as well as menu being edited.  I will see what else can be done to decrease CPU load

**Comment by slawekmikula** [comment]
yes, of course. I wrote it only for indication of error. Something in update function is taking too much time or this loop does not wait for 0.75 second (does refresh allow 0.75 values ?). Maybe it is casted to 0 and that's why this loop is constantly updating.

**Comment by SergKolo** [comment]
@slavekmikula yes, sleep function allows for floating point values. Usually in my scripts I use 0.25, but in this program I used 0.75 . Not sure why I chose that value, probably because i didn't want the menu flicker for the user. Try using 0.25 , and let me know how that works. Otherwise, i can change it to 1 or 2 seconds

**Comment by SergKolo** [comment]
i could also make the change conditionally choose the time. Actually longer sleep time means more load on CPU. So i think we should decrease the value

**Comment by SergKolo** [comment]
@slawekmikula I have added conditional selection of time out and renicing of the process. This should be added into PPA at some point ( it belongs to webupd8 owner , so I can't add it there myself), but you can grab the updated indicator from here, from this repository.  Let me know what you think

**Comment by slawekmikula** [comment]
Right now it does not eats CPU time. Thanks.

**Comment by SergKolo** [comment]
very well, we'll close the issue for now
